version: '3'

volumes:
  pg_vol:
  static:

services:
  pg_db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_vol:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - pg_db
    volumes:
      - static:/backend/collected_static
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    build: ./gateway/
    depends_on:
      - backend
      - frontend
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/
