version: '3'

volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    hostname: pg_db
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: rukiqq/taski_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend/collected_static
    environment:
      WAIT_HOSTS: pg_db:5432
  frontend:
    image: rukiqq/taski_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: rukiqq/taski_gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80
